---
title: "CodeBook"
author: "M Bellettiere"
date: "May 21, 2015"
output: html_document
---

##Variable Names and descriptions

This dataset contains summarized (mean) data for a number of readings taken from the original data.  Subject and Activity are included for each row. In addition, the mean value for each subject and activity have been calculated for each of the 86 measurements listed below. Full details from the original data collection are also included below.

[1] "subject" : (Factor) 1:30 identifying the individual subject for whom the data was collected.   

 [2] "activity"  (Factor) 1:6, labels: walking, walking_upstairs, walking_downstairs, sitting, standing, laying
 
 [3] "tBodyAcc.mean...X"  (numeric) mean value of observations collected for individual
 
 [4] "tBodyAcc.mean...Y"  (numeric) mean value of observations collected for individual
 
 [5] "tBodyAcc.mean...Z"  (numeric) mean value of observations collected for individual                 
 [6] "tBodyAcc.std...X"    (numeric) mean value of observations collected for individual                
 [7] "tBodyAcc.std...Y" (numeric) mean value of observations collected for individual                   
 [8] "tBodyAcc.std...Z" (numeric) mean value of observations collected for individual
 [9] "tGravityAcc.mean...X" (numeric) mean value of observations collected for individual                
[10] "tGravityAcc.mean...Y"  (numeric) mean value of observations collected for individual            
[11] "tGravityAcc.mean...Z"  (numeric) mean value of observations collected for individual          
[12] "tGravityAcc.std...X"  (numeric) mean value of observations collected for individual         
[13] "tGravityAcc.std...Y"    (numeric) mean value of observations collected for individual       
[14] "tGravityAcc.std...Z"   (numeric) mean value of observations collected for individual        
[15] "tBodyAccJerk.mean...X" (numeric) mean value of observations collected for individual        
[16] "tBodyAccJerk.mean...Y" (numeric) mean value of observations collected for individual        
[17] "tBodyAccJerk.mean...Z"  (numeric) mean value of observations collected for individual       
[18] "tBodyAccJerk.std...X" (numeric) mean value of observations collected for individual       
[19] "tBodyAccJerk.std...Y" (numeric) mean value of observations collected for individual   
[20] "tBodyAccJerk.std...Z" (numeric) mean value of observations collected for individual         
[21] "tBodyGyro.mean...X"   (numeric) mean value of observations collected for individual               
[22] "tBodyGyro.mean...Y"   (numeric) mean value of observations collected for individual             
[23] "tBodyGyro.mean...Z"    (numeric) mean value of observations collected for individual              
[24] "tBodyGyro.std...X"    (numeric) mean value of observations collected for individual               
[25] "tBodyGyro.std...Y"      (numeric) mean value of observations collected for individual             
[26] "tBodyGyro.std...Z"     (numeric) mean value of observations collected for individual              
[27] "tBodyGyroJerk.mean...X"   (numeric) mean value of observations collected for individual           
[28] "tBodyGyroJerk.mean...Y"   (numeric) mean value of observations collected for individual           
[29] "tBodyGyroJerk.mean...Z"   (numeric) mean value of observations collected for individual           
[30] "tBodyGyroJerk.std...X"    (numeric) mean value of observations collected for individual           
[31] "tBodyGyroJerk.std...Y"    (numeric) mean value of observations collected for individual/activity           
[32] "tBodyGyroJerk.std...Z"    (numeric) mean value of observations collected for individual/activity           
[33] "tBodyAccMag.mean.."     (numeric) mean value of observations collected for individual/activity                        
[34] "tBodyAccMag.std.."      (numeric) mean value of observations collected for individual/activity                        
[35] "tGravityAccMag.mean.."  (numeric) mean value of observations collected for individual/activity                        
[36] "tGravityAccMag.std.."   (numeric) mean value of observations collected for individual/activity                        
[37] "tBodyAccJerkMag.mean.." (numeric) mean value of observations collected for individual/activity                        
[38] "tBodyAccJerkMag.std.."  (numeric) mean value of observations collected for individual/activity                        
[39] "tBodyGyroMag.mean.."    (numeric) mean value of observations collected for individual/activity                        
[40] "tBodyGyroMag.std.."     (numeric) mean value of observations collected for individual/activity                        
[41] "tBodyGyroJerkMag.mean.."  (numeric) mean value of observations collected for individual/activity                        
[42] "tBodyGyroJerkMag.std.." (numeric) mean value of observations collected for individual/activity                        
[43] "fBodyAcc.mean...X"  (numeric) mean value of observations collected for individual/activity                            
[44] "fBodyAcc.mean...Y"  (numeric) mean value of observations collected for individual/activity                            
[45] "fBodyAcc.mean...Z"  (numeric) mean value of observations collected for individual/activity                            
[46] "fBodyAcc.std...X"   (numeric) mean value of observations collected for individual/activity                            
[47] "fBodyAcc.std...Y"   (numeric) mean value of observations collected for individual/activity                            
[48] "fBodyAcc.std...Z"   (numeric) mean value of observations collected for individual/activity                            
[49] "fBodyAcc.meanFreq...X"  (numeric) mean value of observations collected for individual/activity                        
[50] "fBodyAcc.meanFreq...Y"  (numeric) mean value of observations collected for individual/activity                        
[51] "fBodyAcc.meanFreq...Z"  (numeric) mean value of observations collected for individual/activity                        
[52] "fBodyAccJerk.mean...X"  (numeric) mean value of observations collected for individual/activity                        
[53] "fBodyAccJerk.mean...Y"  (numeric) mean value of observations collected for individual/activity                        
[54] "fBodyAccJerk.mean...Z"  (numeric) mean value of observations collected for individual/activity                        
[55] "fBodyAccJerk.std...X"   (numeric) mean value of observations collected for individual/activity                        
[56] "fBodyAccJerk.std...Y"   (numeric) mean value of observations collected for individual/activity                        
[57] "fBodyAccJerk.std...Z"   (numeric) mean value of observations collected for individual/activity                        
[58] "fBodyAccJerk.meanFreq...X" (numeric) mean value of observations collected for individual/activity                      
[59] "fBodyAccJerk.meanFreq...Y"  (numeric) mean value of observations collected for individual/activity                      
[60] "fBodyAccJerk.meanFreq...Z"  (numeric) mean value of observations collected for individual/activity                    
[61] "fBodyGyro.mean...X"     (numeric) mean value of observations collected for individual/activity                        
[62] "fBodyGyro.mean...Y"     (numeric) mean value of observations collected for individual/activity                        
[63] "fBodyGyro.mean...Z"     (numeric) mean value of observations collected for individual/activity                        
[64] "fBodyGyro.std...X"      (numeric) mean value of observations collected for individual/activity                        
[65] "fBodyGyro.std...Y"      (numeric) mean value of observations collected for individual/activity                        
[66] "fBodyGyro.std...Z"      (numeric) mean value of observations collected for individual/activity                        
[67] "fBodyGyro.meanFreq...X" (numeric) mean value of observations collected for individual/activity                        
[68] "fBodyGyro.meanFreq...Y" (numeric) mean value of observations collected for individual/activity                        
[69] "fBodyGyro.meanFreq...Z" (numeric) mean value of observations collected for individual/activity                        
[70] "fBodyAccMag.mean.."     (numeric) mean value of observations collected for individual/activity                        
[71] "fBodyAccMag.std.."      (numeric) mean value of observations collected for individual/activity                        
[72] "fBodyAccMag.meanFreq.." (numeric) mean value of observations collected for individual/activity                        
[73] "fBodyBodyAccJerkMag.mean.." (numeric) mean value of observations collected for individual/activity                    
[74] "fBodyBodyAccJerkMag.std.."  (numeric) mean value of observations collected for individual/activity                      
[75] "fBodyBodyAccJerkMag.meanFreq.."      (numeric) mean value of observations collected for individual/activity           
[76] "fBodyBodyGyroMag.mean.."  (numeric) mean value of observations collected for individual/activity           
[77] "fBodyBodyGyroMag.std.." (numeric) mean value of observations collected for individual/activity                        
[78] "fBodyBodyGyroMag.meanFreq.."  (numeric) mean value of observations collected for individual/activity           
[79] "fBodyBodyGyroJerkMag.mean.."  (numeric) mean value of observations collected for individual/activity                    
[80] "fBodyBodyGyroJerkMag.std.." (numeric) mean value of observations collected for individual/activity                    
[81] "fBodyBodyGyroJerkMag.meanFreq.."  (numeric) mean value of observations collected for individual/activity           
[82] "angle.tBodyAccMean.gravity."  (numeric) mean value of observations collected for individual/activity           
[83] "angle.tBodyAccJerkMean..gravityMean." (numeric) mean value of observations collected for individual/activity           
[84] "angle.tBodyGyroMean.gravityMean."    (numeric) mean value of observations collected for individual/activity           
[85] "angle.tBodyGyroJerkMean.gravityMean." (numeric) mean value of observations collected for individual/activity           
[86] "angle.X.gravityMean."   (numeric) mean value of observations collected for individual/activity           
[87] "angle.Y.gravityMean." (numeric) mean value of observations collected for individual/activity                        
[88] "angle.Z.gravityMean." (numeric) mean value of observations collected for individual/activity           

##Original Data set descriptions

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation
mad(): Median absolute deviation 
max(): Largest value in array
min(): Smallest value in array
sma(): Signal magnitude area
energy(): Energy measure. Sum of the squares divided by the number of values. 
iqr(): Interquartile range 
entropy(): Signal entropy
arCoeff(): Autorregresion coefficients with Burg order equal to 4
correlation(): correlation coefficient between two signals
maxInds(): index of the frequency component with largest magnitude
meanFreq(): Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean

The complete list of variables of each feature vector is available in 'features.txt'



##The steps to produce the output file are as follows:
* check if data exisits, if not, load data file from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip then unzip file. If data exisits then this is skipped.
* load dplyr - this will create a warning but will not stop execution of code
* load subject data,load test data (y is activity x is variable measurement data)
* load train data y is activity x is variable data
* create tables with subject, activity, readings by cbind in order
* rbind the training and the test sets to create one data set. Merge is not used because it can change the order of data
* Instructions are "Extracts only the measurements on the mean and standard deviation for each measurement." To do this, Look for columns names containing either "-mean" or "-std." Then create vector index of the mean/std columns 
* adjust the indexes for the position of the actual dataset adding the columns for subject and activity
* include selected columns for mean/std and the first two columns (subject and activity)
* Instructions are "Appropriately labels the data set with descriptive variable names."  To do this,set the column names based on the description of the dataset in the features.txt file. Note: These are not entirely friendly but because they are well documented I believe this are appropriately descriptive.
* subset by the vector of selected columns (a) and create a new df
* Instructions are "From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject." I understand this to mean group by subject and activity then calculate mean values. I do so using "group_by" and "summarise each"
* "Uses descriptive activity names to name the activities in the data set" I do so by setting factor levels and labels for activity.
* write final results to table "output.txt"  